export const ItemList = [
    {
        id:'1',
        description: 'tile - 1',
        price: 5.50,
        active: true,
        deleted: false,
    },
    {
        id:'2',
        description: 'tile - 2',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'3',
        description: 'tile - 3',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'4',
        description: 'tile - 4',
        price: 5.50,
        active: true,
        deleted: false,
    },
    {
        id:'5',
        description: 'tile - 5',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'6',
        description: 'tile - 6',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'7',
        description: 'tile - 7',
        price: 5.50,
        active: true,
        deleted: false,
    },
    {
        id:'8',
        description: 'tile - 8',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'9',
        description: 'tile - 9',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'10',
        description: 'tile - 10',
        price: 5.50,
        active: true,
        deleted: false,
    },
    {
        id:'11',
        description: 'tile - 11',
        price: 1.50,
        active: false,
        deleted: false,
    },
    {
        id:'12',
        description: 'tile - 12',
        price: 1.50,
        active: false,
        deleted: false,
    }
]